{% set version = "0.3.0" %}

package:
  name: supermercado
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/supermercado/supermercado-{{ version }}.tar.gz
  sha256: d8cc7519cb25f1142ee0e7c9e40b9be9a5688c3ac1f90a87d165286c3bfe44b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - supermercado = supermercado.scripts.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - click
    - click-plugins
    - cligj
    - mercantile
    - numpy
    - rasterio

test:
  requires:
    - python {{ python_min }}
  imports:
    - supermercado
    - supermercado.scripts
  commands:
    - supermercado --help

about:
  home: https://github.com/mapbox/supermercado
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Supercharged mercantile

extra:
  recipe-maintainers:
    - ocefpaf
